### ISSUE TITLE
Investigate auto documentation for PowerShell scripts

### ISSUE THREAD

**Issue by marclerwick** [Azure/benchpress#104]
There was previous work to auto-generate markdown documents from PowerShell helper comments

- [x] Confirm whether the stated work is indeed complete
- [x] Edit or close #71 based on findings

**Comment by msha1026** [comment]
Auto-generation of markdown documents from PowerShell helper comments is handled by this workflow: https://github.com/Azure/benchpress/blob/main/.github/workflows/publish-docs.yml

This workflow needs to be manually kicked off, and on completion will generate markdown files in a docs folder on a docs branch.

Auto generation in combination with #92 will cover the work outlined in #71. So will close out #71
