### ISSUE TITLE
Investigate publishing to powershell gallery

### ISSUE THREAD

**Issue by munishm** [Azure/benchpress#11]
How to publish the Benchpress module to PowerShell gallery?

Document research so that it can be shared out.

**Comment by craigofnz** [comment]
**FYI:** Potential naming naming conflict  clash in Powershell Gallery with https://www.powershellgallery.com/packages/Benchpress

Really looking forward to giving this framework a roll shortly.

**Comment by hattan** [comment]
Can we publish without unit tests for helpers?

**Comment by msha1026** [comment]
We have documented how to publish to PSGallery in the project Wiki. Have also split handling the naming conflict into a separate issue.
