### ISSUE TITLE
Architecture documentation

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#121]
As an engineer, I would like to create documentation explaining important architecture in the project, so that contributors/maintainers and consumers understand design decisions.

- [ ] Explanation of CI/CD workflow
- [ ] Infrastructure testing overview and best practices? (Can pull from terratest documentation)

**Comment by ozboms** [comment]
This issue should include information from the Wiki:

- For CI/CD task, it should include information about how we're [updating the manifest file with GitVersioning](https://github.com/Azure/benchpress/wiki/Research-Spikes#gitversion). It should also include a look into how we're testing [publication to the powershell gallery](https://github.com/Azure/benchpress/wiki/Research-Spikes#publishing-to-psgallery) using a [local PowerShell gallery](https://github.com/Azure/benchpress/wiki/Research-Spikes#options-for-a-local-repository)

- For the testing task, it should include information about Pester, how importing and mocking works - pulling from the [wiki](https://github.com/Azure/benchpress/wiki/Research-Spikes#unit-testing-in-powershellpester)
