### ISSUE TITLE
Investigate how to implement custom assertions

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#156]
As an engineer I would like to investigate how BenchPress could leverage Pester's custom assertions.

Pester allows developers to define their own [custom assertions](https://pester.dev/docs/assertions/custom-assertions). Could we use this in some way so that we can create an assertion that a user of BenchPress could use? (i.e. Should-BeAvailable when checking if a resource exists) How would we bootstrap this custom assertion into the BenchPress module?

- [x] Document investigation and come to agreement with team
- [x] Create subsequent issues for follow up implementation
- [x] Bring to design session for discussion around implementation details
- [x] Update #147 with correct acceptance criteria

**Comment by jasonshortphd** [comment]
Leaving design in Milestone 2.  Implementation can move to Milestone 3.

**Comment by ozboms** [comment]
Wiki is updated [here ](https://github.com/Azure/benchpress/wiki/Research-Spikes#custom-assertions)to close out this task with investigation findings.
