### ISSUE TITLE
DataLakeStorage support

### ISSUE THREAD

**Issue by jansepapenfus1** [Azure/benchpress#183]
As an engineer, I would like to create a function/cmdlet to support DataLakeStorage checks so that we can support future customer's needs.

- [ ] Create `Confirm-DataLakeStorage.ps1` and unit tests
- [ ] Wire up `Confirm-DataLakeStorage` to `Common.ps1`
- [ ] Create example tests, bicep and documentation in `examples` folder

**Comment by marclerwick** [comment]
This is a no-op.

Storage for ADLS is now wholly contained by Azure Storage, which has already been addressed in BenchPress.

Data Lake Store Account (note Store and not Storage) is deprecated with ADLS Gen1, so will not be added.
