### ISSUE TITLE
StreamAnalytics support

### ISSUE THREAD

**Issue by jansepapenfus1** [Azure/benchpress#189]
As an engineer, I would like to create a function/cmdlet to support StreamAnalytics checks so that we can support future customer's needs.

- [ ] Create `Confirm-StreamAnalytics.ps1` and unit tests
- [ ] Wire up `Confirm-StreamAnalytics` to `Common.ps1`
- [ ] Create example tests, bicep and documentation in `examples` folder

**Comment by msha1026** [comment]
This is not possible/is a dupe of the child issues (Cluster and Jobs). Will be covered by issues #190, #191, #192, #193, #194, #195. Closing this issue.
