### ISSUE TITLE
Data Factory V1 support

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#222]
As an engineer, I would like to create a function/cmdlet to support DataFactory V1 checks so that we can support future customer's needs.

- [ ] Create `Confirm-DataFactoryV1.ps1` and unit tests
- [ ] Wire up `Confirm-DataFactory`V1 to `Common.ps1`
- [ ] Create example tests, bicep and documentation in `examples` folder

**Comment by quigg-caroline** [comment]
Blocked, but waiting for confirmation that bicep does not support v1
