### ISSUE TITLE
Address inconsistencies in comments, naming, casing, etc.. Part 1 for the `examples` directory

### ISSUE THREAD

**Issue by marclerwick** [Azure/benchpress#245]
Throughout the code base there are inconsistencies in various aspects of the comments, naming, casing, etc.

As a developer/user, I want consistent comments, naming, casing, etc. so that when I read the code, or see output it is consistent from one interaction to the next.

In the `examples` folder:
- [x] sometimes the output string reads "...with the given name..." sometimes it reads "...named xyz...".
- [x] sometimes the `It` block is capitalized, sometimes it is not (it should be capitalized).
- [x] `.md` files sometimes the "replace" variables are aligned, sometimes they're not.
- [x] Using conjugated names instead of full names in the description string of unit tests and examples (e.g., `keyVault` instead of `Key Vault`, `EventHub` instead of `Event Hub`, `Sql` or `sql` instead of `SQL`; i.e., the proper names).
- [x] splatted variables are aligned, sometimes they're not.
- [x] Locally defined variables should be lower cased
- [x] Update file encoding to UTF-8 w/BOM
- [x] import and export Az.InfrastructureTesting
- [x] Add `PropertyType` and `PropertyKey` to descriptions in `Confirm-AzBPResource` examples

Acceptance criteria:
- [ ] Thoroughly go through the code base to find any inconsistencies
- [ ] Correct the inconsistencies

**Comment by ozboms** [comment]
More tings:

- [ ] Update comments to #act and #assert
- [ ] Fix line lengths (either splat or move to a new line)
