### ISSUE TITLE
Key Vault Access Policy Support

### ISSUE THREAD

**Issue by marclerwick** [Azure/benchpress#259]
As an engineer, I would like to create a function/cmdlet to support Key Vault Access Policy so that we can support future customer's needs.

The bicep resource is `Microsoft.KeyVault/vaults/accessPolicies`

- [ ] ~~Create `Confirm-KeyVaultAccessPolicy.ps1` and unit tests~~
- [ ] ~~Add `KeyVaultAccessPolicy` to `ResourceType` enum~~
- [ ] ~~Wire up `Confirm-KeyVaultAccessPolicy` to `Get-ResourceByType.ps1`~~
- [ ] Create example tests, bicep and documentation in `examples` folder

**Comment by msha1026** [comment]
There is no Az PowerShell command along the lines of `Get-AzKeyVaultAccessPolicy` and `Confirm-AzBPResource` supports checking access policies. The following test would work:

```
$params = @{ 
    ResourceType = "KeyVault" 
    ResourceGroupName = "rg-test" 
    ResourceName = "testkv" 
    PropertyKey = "AccessPolicies[0].ApplicationId" 
    PropertyValue = "<app-id-for-svc-prin>"
}

Confirm-AzBPResourse @params | Should -BeSuccessful
```

Changing this issue to add examples of how to do this to the `examples` directory.
