### ISSUE TITLE
Portal Dashboards support

### ISSUE THREAD

**Issue by marclerwick** [Azure/benchpress#260]
As an engineer, I would like to create a function/cmdlet to support Portal Dashboards so that we can support future customer's needs.

The bicep resource is `Microsoft.Portal/dashboards`

- [ ] Create `Confirm-PortalDashboard.ps1` and unit tests
- [ ] Add `PortalDashboard` to `ResourceType` enum
- [ ] Add `PortalDashboard.cs` to `BenchPress\Generators\ResourceTypes` folder
- [ ] Wire up `Confirm-PortalDashboard` to `Get-ResourceByType.ps1`
- [ ] Create example tests, bicep and documentation in `examples` folder

**Comment by msha1026** [comment]
Little update/FYI: https://github.com/Azure/azure-powershell/issues/21363#issuecomment-1496724906
