### ISSUE TITLE
Unit tests for Generator

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#271]
Currently there are no unit tests written for the Generator code. In order to follow engineering fundamentals, I would like to write unit tests to cover the Generator code and ensure it works with our current CI/CD process.

- [x] Test folder structure created
- [x] Unit tests created
- [x] Ensure unit tests successfully run as a part of existing Github actions

**Comment by quigg-caroline** [comment]
#324  sets up initial unit test project and adds initial unit tests for the project.
