### ISSUE TITLE
Spike: research best practices for structure of Generator code

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#275]
As an engineer, I would like to do the research for the structure of the Generator code to follow any .NET best practices when it comes to folder structure.

- [x] Folder structure researched, and recommendations documented

**Comment by marclerwick** [comment]
So, the short answer is there is no single best practice. Many of the opinions on the subject are quite old and were recommendations when monoliths and layered architectures were predominant. Sifting through the noise to get to more recent opinions and recommendations resulted in the following:

Simple Single Solution/Project example: https://github.com/dotnet/samples/tree/main/framework/libraries/migrate-library-csproj-keep-existing
Organizing for multiple .NET versions: https://learn.microsoft.com/en-us/dotnet/core/porting/project-structure
Overall Project Recommendation: https://gist.github.com/davidfowl/ed7564297c61fe9ab814
Clean Architeture: https://github.com/jasontaylordev/CleanArchitecture


Given that there is only a single Solution/Project the only real consideration is adding additional Solutions/Projects. The current structure is:

```
root
 |- ...
 |- BenchPress
    |- bicep (git submodule)
    |- Generators
       |- ...
       |- Generators.csproj
    |- BenchPress.sln
 |- ...
```

The recommendation would be to migrate to a `src`/`test` structure within the Solution root and further expand the namespaces:

```
root
 \- ...
 \- TestGenerator
    \- src
       \- bicep (git submodule)
       \- Azure
          \- Resources
             |- ActionGroup.cs
             |- AksCluster.cs
             |- ...
          |- Azure.csproj
       \- Generator
          \- Common
             \- Exceptions
                |- UnknownResourceTypeException.cs
             \- Test
                |- Definition.cs
                |- Metadata.cs
                |- SdkFunction.cs
                |- TestType.cs
             \- Transformation
                |- AzureTemplateImporter.cs
                \- Providers
                   |- ILanguageProvider.cs
                   |- PowerShellLanguageProvider.cs
                |- TestViewModel.cs
          |- Generator.cs
          |- Generator.csproj
          |- Program.cs
       \- Templates
          \- PowerShell
             |- template.ps1
    \- tests
       \- Azure.Tests
          \- Resources
             |- ActionGroupTest.cs
             |- AksClusterTest.cs
             |- ...
          |- Azure.Tests.csproj
       \- Generator.Tests
          \- Common
             \- Exceptions
                |- UnknownResourceTypeExceptionTest.cs
             \- Test
                |- DefinitionTest.cs
                |- MetadataTest.cs
                |- SdkFunctionTest.cs
                |- TestTypeTest.cs
             \- Transformation
                |- AzureTemplateImporterTest.cs
                \- Providers
                   |- PowerShellLanguageProviderTest.cs
                |- TestViewModelTest.cs
          |- GeneratorTest.cs
          |- Generator.Tests.csproj
          |- ProgramTest.cs
    \- TestGenerator.sln
 \- New Solution (same structure as TestGenerator)
 \- ...
```

**Comment by marclerwick** [comment]
Tagging @msha1026 @ozboms @quigg-caroline @hattan @polatengin

**Comment by msha1026** [comment]
Really digging this suggested implementation. A probably dumb question on my end, what is the reasoning of separating `Azure` out to its own project and not have it as a directory under the `Generator` project?

**Comment by marclerwick** [comment]
> Really digging this suggested implementation. A probably dumb question on my end, what is the reasoning of separating `Azure` out to its own project and not have it as a directory under the `Generator` project?

I went back and forth on this, but in the end, I looked at the `Generator` project as the code that actually does the generation, and the `Azure` project as the kind of like the interface (or like the glue) between Azure/bicep and the Generator. Logically (in my mind at least), it made sense to have a separate project that had all of the code to work with Azure/bicep.
