### ISSUE TITLE
Address inconsistencies in comments, naming, casing, etc.. Part 3

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#293]
Throughout the code base there are inconsistencies in various aspects of the comments, naming, casing, etc.

As a developer/user, I want consistent comments, naming, casing, etc. so that when I read the code, or see output it is consistent from one interaction to the next.

In the `Modules/BenchPress.Azure/:
- [x] Update file encoding to UTF-8 w/BOM
- [ ] Ensure all code comments have complete sentences with correct punctuation.

Acceptance Critera
- [ ] Thoroughly go through the code base to find any inconsistencies
- [ ] Correct the inconsistencies

**Comment by ozboms** [comment]
- [ ] Add `PropertyType` and `PropertyKey` to descriptions in `Confirm-AzBPResource` examples

**Comment by msha1026** [comment]
I will be closing this issue and moving the action items into existing issues to better align with the outstanding PRs. Hopefully this will make it easier to track which PR is applying what changes.

"Update file encoding" has been moved to both #285 and #245.
"Ensure all code comments have complete sentences and correct punctuation" has been moved to #285.
"Add `PropertyType` and `PropertyKey` to descriptions in `Confirm-AzBPResource` examples" has been moved to #245.

If there are more inconsistencies, please add to #285 and/or #245.
