### ISSUE TITLE
Come with a naming convention for Benchpress cmdlets

### ISSUE THREAD

**Issue by polatengin** [Azure/benchpress#32]
Currently benchpress helper functions are named like, Get-XXX, Get-XXXExists

Should we add Benchpress or part of it in the naming, like, Get-BenchXXX, etc?

_Acceptance Criteria_

- [ ] Decide a naming schema
- [ ] Update helpers according to the schema

**Comment by msha1026** [comment]
Adding context from our design session: PowerShell ScriptAnalyzer also throws warnings on cmdlets that end with "Exists" because it doesn't recommend using plural nouns. Need to come to a consensus on how to refactor cmdlets that end with "Exists".
