### ISSUE TITLE
Create bicep helper

### ISSUE THREAD

**Issue by polatengin** [Azure/benchpress#43]
_Acceptance Criteria_

- [ ] Create helper method to run bicep build for linting

**Comment by marclerwick** [comment]
The following command will store any errors as `System.Management.Automation.ErrorRecord` in the `$response` object.

`$response = Invoke-Command -ScriptBlock {bicep build actionGroup.bicep 2>&1}`

**Comment by marclerwick** [comment]
This also implies that the bicep CLI must be installed on the build agent.
