### ISSUE TITLE
Investigate setting up a private PowerShell gallery

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#79]
PSGallery recommends using a private/local PSGallery when it comes to testing publishes to a PSGallery. The documentation can be found here: https://learn.microsoft.com/en-us/powershell/scripting/gallery/concepts/publishing-guidelines?view=powershell-7.3#test-using-a-local-repository. However some of it seems to be outdated. Investigate and document how to setup a local PSGallery.

**Comment by ozboms** [comment]
Did a deep dive into the options for setting up a private repository and have posted findings on the wiki page.

Conclusions:
We will use a Nuget.Server (.NET Core) and containerize it to be deployed and destroyed only in the pipeline. It will spin up, test publication of the module, and then spin down.
