### ISSUE TITLE
Create CI pipeline with non-PSGallery dependent tasks

### ISSUE THREAD

**Issue by marclerwick** [Azure/benchpress#84]
This is essentially a sub-task of a larger "Create CI/CD Pipeline" user story.

The focus of this user story is to create the portion of the CI/CD pipeline that executes when a merge occurs into the main branch. The following are requirements of the pipeline when code is merged into `main`:

- [ ] The Solution is built - any failure to build prevents subsequent pipeline steps.
- [ ] All unit tests are executed - any failure prevents subsequent pipeline steps.

Pre-req: 
- [ ] Unit test created #67

**Comment by msha1026** [comment]
I added task #88 to reflect the need to create our first integration test. Can decide tomorrow if we want to keep that task separated or perhaps merge into this task.

**Comment by msha1026** [comment]
Splitting this issue into two issues. One for non-PSGallery dependent tasks and one for PSGallery dependent tasks.
