### ISSUE TITLE
Consider new name for Project.

### ISSUE THREAD

**Issue by marclerwick** [Azure/benchpress#87]
The name Benchpress is already used in the PSGallery and therefore would be a conflict. We need to decide on a path forward for naming at the earliest possible point, so the minimum refactoring is necessary.

**Comment by hattan** [comment]
Team decided to keep the BenchPress name for the project and use Az.InfrastructureTesting for the powershell gallery,

**Comment by marclerwick** [comment]
@hattan 
Are you going to create a "refactoring" ticket for the new gallery name?
Also, what will the new prefix be, since AzBP wouldn't fit anymore?
